#! /bin/sh

BSPWM_CONFIG=$HOME/.config/bspwm
POLYBAR_CONFIG=$HOME/.config/polybar
WALLPAPERS=$HOME/wallpapers

bspc config pointer_motion_interval 40

source $HOME/arch-linux-setup/god-mode/etc/profile.d/monitors.sh
source $BSPWM_CONFIG/monitor-setup.sh
source $POLYBAR_CONFIG/launch.sh
source $BSPWM_CONFIG/rules.sh
source $BSPWM_CONFIG/styling.sh

# Autostart
dex -a

# Set wallpaper
RANDOM_WALLPAPER=$(find $WALLPAPERS/* -xtype f | shuf -n 1) &&
	feh --bg-fill "$RANDOM_WALLPAPER"
