#! /bin/sh

export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

BSPWM_CONFIG=$HOME/.config/bspwm
POLYBAR_CONFIG=$HOME/.config/polybar
WALLPAPERS="$HOME"/wallpapers

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &
pgrep -x picom > /dev/null || picom &

source $BSPWM_CONFIG/monitor-setup.sh
source $POLYBAR_CONFIG/launch.sh
source $BSPWM_CONFIG/rules.sh
source $BSPWM_CONFIG/styling.sh

# Autostart
dex -a

# Set wallpaper
RANDOM_WALLPAPER=$(find $WALLPAPERS/* -xtype f | shuf -n 1) &&
	feh --bg-fill "$RANDOM_WALLPAPER"
