xrdb $HOME/.config/X11/xresources

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &
pgrep -x picom > /dev/null || picom &
pgrep -x ntfd > /dev/null || ntfd &

# activate screen locker
xset s 300 20
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- env XSECURELOCK_NO_COMPOSITE=1 env XSECURELOCK_SAVER=saver_blank xsecurelock &

exec bspwm
