#!/bin/bash

awk '/^[a-z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""}
/^#/{last=$0}' $HOME/.config/sxhkd/sxhkdrc{,.common} |
    column -t -s $'\t' |
    #$HOME/.config/rofi/config-sxhkd-help.rasi | rofi -dmenu -i -markup-rows -no-show-icons -width 100 -lines 15 -yoffset 40
    rofi -dmenu -i -markup-rows -no-show-icons -width 1000 -lines 15 -yoffset 40
